version: '3'
services:
  rabbitmq_node1:
    image: rabbitmq:management-alpine
    container_name: rabbitmq_node1
    hostname: rabbitmq_node1
    volumes:
      - ./node1/data:/var/lib/rabbitmq/
      - ./node1/log:/var/log/rabbitmq/
    ports:
      # - 5672:5672
      - 15672:15672
    networks:
      - rabbitmqnet
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  rabbitmq_node2:
    image: rabbitmq:management-alpine
    container_name: rabbitmq_node2
    hostname: rabbitmq_node2
    ports:
      # - 5673:5672
      - 15673:15672
    volumes:
      - ./node2/data:/var/lib/rabbitmq/
      - ./node2/log:/var/log/rabbitmq/
    networks:
      - rabbitmqnet
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  rabbitmq_node3:
    image: rabbitmq:management-alpine
    container_name: rabbitmq_node3
    hostname: rabbitmq_node3
    ports:
      # - 5674:5672
      - 15674:15672
    volumes:
      - ./node3/data:/var/lib/rabbitmq/
      - ./node3/log:/var/log/rabbitmq/
    networks:
      - rabbitmqnet
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
networks:
  rabbitmqnet:
    name: rabbitmqnet